name: Run Trading Bot with Auto-Restart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-binance python-telegram-bot pandas matplotlib pytz numpy

      - name: Set Environment Variables
        run: |
          echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" >> $GITHUB_ENV
          echo "BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }}" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Run Bot with Auto-Restart
        run: |
          while true; do
            python main.py 2>&1 | tee bot.log
            echo "Bot crashed or stopped. Restarting in 5 seconds..."
            sleep 5
          done