name: Run Trading Bot

on:
  schedule:
    # Run every 1 minute
    - cron: "*/1 * * * *"
    # Run every 5 minutes
    - cron: "*/5 * * * *"
    # Run every 15 minutes
    - cron: "*/15 * * * *"
    # Run every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 4: Run Bot
      - name: Run Trading Bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py